version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
         name: Installing Dependencies
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install -r requirements
      - run:
         name: Unit Testing
         command:: 'python -m unittest discover -v'
